import os
from time import sleep

os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_create_new_account.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_add_dependents.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_medical_test_antibody_cvs_pharmacy.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_medical_test_antibody_inspire_health.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_medical_test_antigen_cvs_pharmacy.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_medical_test_antigen_inspire_health.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_medical_test_pcr_cvs_pharmacy.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_medical_test_pcr_inspire_health.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_vaccination_covid_19_vaccine_cvs_pharmacy.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_vaccination_covid_19_vaccine_inspire_health.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_for_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_home_kit_order_antibody.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_home_kit_order_antigen.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_home_kit_order_antigen_self_kit.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_appointment_virtual_appointment_inspire_health.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_schedule_virtual_appointment_for_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_cancel_scheduled_appointment.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_cancel_schedule_appointment_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")

os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_enable_email_notifications.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_enable_push_notifications.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_enable_sms_notifications.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_disable_email_notifications.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_disable_push_notifications.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_disable_sms_notifications.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_download_qr_code.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_reset_id.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_view_scan_history.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_PCR_Test.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_PCR_Test_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_vaccination_CDC.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_vaccination_CDC_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_vaccination_inspire_health.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_vaccination_inspire_health_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_COVID_19_Test_Antigen_CDC.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_COVID_19_Test_Antigen_CDC_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Immunization.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Immunization_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_19_Test_Antibody.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_19_Test_Antibody_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_19_rt_pcr.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_health_Covid_19_rt_pcr_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_passport.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_passport_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_texas_driver_license.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_texas_driver_license_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_alabama_driver_license.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_alabama_driver_license_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_alaska_driver_license.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_alaska_driver_license_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_student_card.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_link_record_id_student_card_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_edit_basic_information.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_edit_contact_information.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_edit_additional_profile_information.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_edit_dependent_account_details.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
# os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_edit_dependent_additional_profile_info.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_delete_dependent.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
os.system("pytest C://Users//ReddySaS//PycharmProjects//Upass-2.0//tests//test_holder//test_delete_account.py --alluredir=C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")


sleep(15)

os.system("allure serve C://Users//ReddySaS//PycharmProjects//Upass-2.0//Reports")
