"""
@authors        : Indudhara, Sreenivas reddy, Soma sekhar
Description    : This class is used to store all the upass elements
"""


class UpassPortalElements:
    continue_btn = "//div[text()='continue']"
    continue_btn_2 = "(//div[text()='continue'])[2]"
    continue_btn_4 = "(//div[text()='continue'])[3]"
    get_started_btn = "//div[text()='get started']"


class CreateNewLoginElements:
    create_new_login_btn = "//div[text()='create new login']"
    full_name = "//input[@type='text']"
    continue_btn = "//div[text()='continue']"
    enter_email = "//input[@type='email']"
    birthdate = "(//input[@type='tel'])[1]"
    phone_number = "(//input[@type='tel'])[2]"
    password = "(//input[@type='password'])[1]"
    confirm_password = "(//input[@type='password'])[2]"
    insurance_provider = "//input[@placeholder='Insurance Provider']"
    insurance_provider_1 = "(//div[text()='Create New'])/following::div[45]"
    member_id_1 = "(//div[text()='Create New'])/following::div[55]"
    group_number_1 = "(//div[text()='Create New'])/following::div[65]"
    member_id = "//input[@placeholder='Member ID']"
    group_number = "//input[@placeholder='Group Number']"
    sex = "(//input[@class='css-11aywtz r-16y2uox r-ubezar r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[8]"
    gender_m = "(//div[text()='Male'])"
    race = "(//input[@class='css-11aywtz r-16y2uox r-ubezar r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[9]"
    race_w = "//div[text()='White']"
    ethnicity = "(//input[@class='css-11aywtz r-16y2uox r-ubezar r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[10]"
    ethnicity_h = "//div[text()='Hispanic']"
    push_notifications = "(//div[@class='css-1dbjc4n r-1awozwy r-z80fyv r-1777fci r-19wmn03'])[1]"
    sms_notifications = "(//div[@class='css-1dbjc4n r-1awozwy r-z80fyv r-1777fci r-19wmn03'])[2]"
    i_agree = "(//div[@class='css-1dbjc4n r-1awozwy r-z80fyv r-1777fci r-19wmn03'])[3]"
    verify_authentication_page = "//div[text()='Two Factor']"
    go_to_upass_btn = "//div[text()='go to u-pass']"
    verify_email = "//p[text()='Your email address was successfully verified.']"
    verify_registration_logo = "//div[@class='css-1dbjc4n r-1awozwy r-13awgt0 r-z80fyv r-1777fci r-199wky7']"


class LoginExistingAccount:
    existing_account = "//div[contains(text(),'Log In to an existing account')]"
    username_tb = "//input[@id='username']"
    password_tb = "//input[@id='password']"
    sign_in_btn = "//button[contains(text(),'Continue')]"
    hamburger_icon = "(//div[@class='css-1dbjc4n r-1awozwy r-z80fyv r-1777fci r-19wmn03'])[1]/../../div[1]"
    reset_id = "(//div[@role='menuitem'])[1]"
    view_scan_history = "(//div[@role='menuitem'])[2]"
    download_code = "(//div[@role='menuitem'])[3]"
    get_care = "(//div[@class='css-1dbjc4n r-1awozwy r-sculcy r-z2wwpe r-156ut6 r-18u37iz r-1777fci r-5wp0in r-1yzf0co'])[1]"
    get_care_btn = "//div[text()='Get Care']"
    appointments_btn = "//div[text()='Appointments']"
    schedule_appointment = "//div[text()='My Appointments']//following::div[12]"
    schedule_new_appointment = "(//div[text()='Schedule New Appointment'])[1]"
    dependent_schedule_appointment_1 = "(//div[text()='(Dependent)']//following::div[5])[1]"
    dependent_schedule_appointment = "(//div[text()='(Dependent)']//following::div[5])[1]"
    no_appointments = "//div[text()='No appointments available']"
    view_dependent_appointment = "(//div[text()='(Dependent)']/following::div[text()='APPOINTMENT'])[1]"
    schedule_date_next = "//div[text()='No appointments available']/../../div/div[3]"
    service_category = "//div[text()='Appointment Type']//following::div[7]"
    service_category_covid_testing = "//div[text()='COVID Testing']"
    service_type_virtual = "//div[text()='Virtual']"

    service_category_medical = "//div[text()='Medical Test']"
    service_category_vaccination = "//div[text()='Vaccination']"
    virtual_appointment = "//div[text()='Service Category']/../../div[2]/div/div[3]"
    service_type_virtual_appointment = "//div[text()='Service Type']/../../div[2]/div/div[1]"
    service_type = "//input[@placeholder='Service Type']"
    service_type_covid_vaccine = "//div[text()='Service Type']/../../div[2]/div/div[1]"
    service_type_antibody_test = "//div[text()='Service Type']/../../div[2]/div/div[1]"
    service_type_antibody_test_2 = "(//div[text()='COVID-19 Antibody Test'])[2]"
    service_type_antigen_test = "//div[text()='Service Type']/../../div[2]/div/div[2]"
    service_type_antigen_test_2 = "(//div[text()='COVID-19 Antigen Test'])[2]"
    service_type_pcr_test = "//div[text()='Service Type']/../../div[2]/div/div[3]"
    service_type_pcr_test_2 = "(//div[text()='COVID-19 PCR Test'])[2]"
    issuer_btn = "(//div[text()='Issuer']/following::div[@class='css-1dbjc4n r-1awozwy r-1fuqb1j r-18u37iz r-h3s6tt r-1777fci r-ymttw5 r-1yzf0co'])[2]"
    choose_appointment_btn = "//div[text()='Choose Appointment']/../../div[2]"
    your_info_btn = "//div[text()='Your Information']/../../div[2]"
    additional_questions = "//div[text()='Additional Questions']/../../div[2]"
    next_btn = "//div[text()='Next']"
    schedule_btn = "//div[text()='Schedule']"
    appointment_scheduled_message = "//div[contains(text(),'Appointment scheduled')]"
    view_appointment = "(//div[text()='APPOINTMENT'])[1]"
    edit_appointment = "//div[text()='Edit']"
    issuer_type_any = "//div[text()='Any']/../../div[1]/div/div[1]"
    issuer_type_cvs = "//div[text()='CVS Pharmacy']/../../div[2]/div/div[1]"
    issuer_type_inspire = "//div[text()='Inspire Health']/../../div[3]/div/div[1]"
    virtual_issuer_type_inspire = "//div[text()='Inspire Health']/../../div[2]/div/div[1]"
    find_a_slot = "(//div[text()='Find a slot'])[1]"
    book_slot = "//div[text()='Choose Appointment']/../../../div[2]/div/../div[2]/div"
    reschedule_slot = "//div[text()='Choose Appointment']/../../../div[2]/div/../div[3]/div"
    confirm_slot = "//div[text()='Choose Appointment']/../../../div[2]/div/../div[2]/div"
    confirm_reschedule_slot = "//div[text()='Choose Appointment']/../../../div[2]/div/../div[3]/div"
    cancel_appointment = "(//div[text()='Cancel Appointment'])[1]"
    confirm_cancel_appointment = "(//div[text()='Cancel Appointment'])[3]"
    confirm_cancel_appointment_message = "//div[text()='Appointment Successfully Cancelled']"
    error_message_cancel_appointment = "//div[text()='Something went wrong. Please try again.']"
    covid_test_yes = "//div[text()='Yes']/../div[1]/div/div/div[1]"
    covid_test_no = "//div[text()='No']/../div[3]/div/div/div[1]"
    fever_chills = "//div[text()='Fever / Chills']/../div/div/div[1]"
    nausea = "//div[text()='Nausea']/../div/div/div[1]"
    headache = "//div[text()='Headache']/../div/div/div[1]"
    dizziness = "//div[text()='Dizziness']/../div/div/div[1]"
    fatigue = "//div[text()='Fatigue']/../div/div/div[1]"
    difficulty_breathing = "//div[text()='Difficulty Breathing']/../div/div/div[1]"
    allergies = "//textarea[@class='css-11aywtz r-16y2uox r-ubezar r-crgep1 r-779j7e r-1h71sx3 r-fdjqy7 r-184en5c']"
    gender = "//div[text()='What is your gender?*']/following::div[@class='css-18t94o4 css-1dbjc4n r-1awozwy r-1loqt21 r-1777fci r-5scogr r-1udh08x r-bnwqim r-ipm5af']"
    gender_m = "//div[text()='Male']"
    gender_f = "//div[text()='Female']"
    gender_others = "//div[text()='Other']"
    prefer_not_to_say = "//div[text()='Prefer not to say']"
    i_am_over_18 = "//div[text()='I am over 18']/../div/div"
    skip = "//div[text()='Skip']"
    review_all_details = "//div[text()='Review All Details']"
    confirm_appointment = "//div[text()='Confirm Appointment']"
    address_field = "//div[text()='What is your address?*']/following::input"
    confirm_logout = "//div[contains(text(),'Confirm')]"
    profile_button = "//span[text()='Profile']"
    dismiss_button = "//div[text()='Dismiss']"
    resend_code = "//div[text()='RESEND CODE']"
    account_details_tb = "(//div[text()='Account Details'])[1]"
    basic_info_edit_btn = "(//div[text()='Edit'])[1]"
    contact_info_edit_btn = "(//div[text()='Edit'])[2]"
    edit_name = "(//input[@type='text'])[1]"
    edit_display_name = "(//input[@type='text'])[2]"
    edit_birthday = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[2]"
    save_btn = "//div[text()='save']"
    cancel_btn = "//div[text()='cancel']"
    secondary_email_edit = "(//input[@type='email'])[2]"
    edit_phone_number = "//input[@type='tel']"
    additional_profile_information_tb = "(//div[text()='Additional Profile Information'])[1]"
    additional_info_edit_btn = "//div[text()='edit']"
    edit_gender = "//div[text()='Additional Info']/following::input[1]"
    gender_male = "//div[text()='Male']"
    gender_female = "//div[text()='Female']"
    edit_sex = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[1]"
    edit_race = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[2]"
    race_white = "//div[text()='White']"
    race_asian = "//div[text()='Asian']"
    race_african_american_black = "//div[text()='African American or Black']"
    race_native_american_alaskan = "//div[text()='Native American or Alaskan']"
    race_pacific_islander_hawaiian = "//div[text()='Pacific Islander or Hawaiian']"
    race_other = "//div[text()='Other']"
    edit_ethnicity = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[3]"
    ethnicity_hispanic = "//div[text()='Hispanic']"
    ethnicity_non_hispanic = "//div[text()='Non-Hispanic']"
    ethnicity_unknown = "//div[text()='Unknown']"
    ethnicity_not_specified = "//div[text()='Not Specified']"
    edit_age = "(//input[@type='text'])[2]"
    name_edit_add_info = "(//input[@type='text'])[3]"
    edit_birthday_add_info = "//input[@type='tel']"
    add_insurance_provider = "(//div[text()='Additional Info'])/following::div[45]"
    add_insurance_provider1 = "(//input[@type='text'])[4]"
    add_member_id = "(//input[@type='text'])[5]"
    add_group_number = "(//input[@type='text'])[6]"
    notification_preferences_tb = "//div[text()='Notification Preferences']"
    email_toggle_bar = "(//input[@class='r-1p0dtai r-1ei5mc7 r-1pi2tsx r-1d2f490 r-crgep1 r-orgf3d r-t60dpp r-u8s1d r-zchlnj r-ipm5af r-13qz1uu'])[1]"
    sms_toggle_bar = "(//input[@class='r-1p0dtai r-1ei5mc7 r-1pi2tsx r-1d2f490 r-crgep1 r-orgf3d r-t60dpp r-u8s1d r-zchlnj r-ipm5af r-13qz1uu'])[2]"
    push_notifications_toggle_bar = "(//input[@class='r-1p0dtai r-1ei5mc7 r-1pi2tsx r-1d2f490 r-crgep1 r-orgf3d r-t60dpp r-u8s1d r-zchlnj r-ipm5af r-13qz1uu'])[3]"
    success_message = "//div[text()='Changes to your notifications have been saved!']"
    auto_approvals_btn = "//div[text()='Auto-Approvals']"
    dependents_add_btn = "//div[text()='Add']"
    dependent_name = "//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'][1]"
    # dependent_name = "//input[@type='text']"
    dependent_birthday = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[2]"
    account_details_dependent = "(//div[text()='Account Details'])[2]"
    basic_info_edit_dependent = "//div[text()='edit']"
    name_dependent = "//input[@type='text']"
    dob_dependent = "//input[@type='tel']"
    add_info_dependent = "(//div[text()='Additional Profile Information'])[2]"
    add_info_dependent_edit = "//div[text()='edit']"
    add_info_dependent_gender = "(//input[@type='text'])[1]"
    add_info_dependent_age = "(//input[@type='text'])[2]"
    add_info_dependent_name = "(//input[@type='text'])[3]"
    auto_approvals_dependent = "(//div[text()='Auto-Approvals'])[2]"
    sign_out_btn = "//div[text()='Sign Out']"
    sign_out_confirm_btn = "//div[text()='Confirm']"
    reset_password_btn = "//div[text()='Reset Password']"
    reset_success = "//div[text()='Password Reset Email Sent!']"
    reset_password_done = "//div[text()='done']"
    delete_account_btn = "//div[text()='Delete Account']"
    confirm_delete_btn = "(//div[text()='Delete'])[2]"
    verify_delete = "//div[text()='Account Successfully Deleted']"
    request_my_data_btn = "//div[text()='Request My Data']"
    call_btn = "//div[text()='Call: XXX-XXX-XXXX']"
    verify_dependent_text = "//div[text()='Dependent has been successfully added.']"
    verify_dependent = "//div[text()='Dependents']//following::div[19]"
    verify_dependent_name = "//div[text()='Dependents']//following::div[19]"
    delete_dependent_button = "(//div[@class='css-1dbjc4n r-1awozwy r-z80fyv r-1777fci r-1kb76zh r-19wmn03'])[3]"
    confirm_delete_dependent_button = "(//div[text()='Delete'])[3]"
    verify_delete_dependent = "//div[@class='css-1dbjc4n r-1awozwy r-z2wwpe r-1quu1zo r-18u37iz r-ymttw5']"

    at_homekit_btn = "//div[text()='At-Home Kit Orders']"
    start_order = "//div[text()='Start Order']"
    order_antigen_kit = "(//div[text()='COVID-19 Antigen Test']/../../div/div/div[2]/div[3])[1]"
    order_antibody_kit = "(//div[text()='COVID-19 Antibody Test']/../../div/div/div[2]/div[3])[2]"
    order_antigen_kit1 = "//div[text()='COVID-19 Antigen Test']//following::div[9]"
    order_pcr_kit = "//div[text()='COVID-19 PCR Test']//following::div[9]"
    order_test_product = "//div[text()='COVID-19 PCR Test']//following::div[9]"
    order_non_zero_product = "//div[text()='Test Non-Zero Product']//following::div[9]"
    place_order = "//div[text()='Place Order']"
    order_Antigen_Self_Test = "(//div[text()='COVID-19 Antigen Self-Test at Home Kit']/../../div/div/div[2]/div[3])[3]"
    check_out = "//div[text()='CHECK OUT']"
    shipping_fullname = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[1]"
    shipping_phone_number = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[2]"
    shipping_address = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[3]"
    shipping_address_input = "(//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c'])[3]/following::div[@class='css-901oao r-cqee49 r-vnw8o6 r-1b43r93 r-16dba41 r-135wba7'][1]"
    shipping_next = "//div[text()='Next']"
    card_number = "//input[@id='Field-numberInput']"
    expiry_date = "//input[@id='Field-expiryInput']"
    cvc = "//input[@id='Field-cvcInput']"
    submit = "//div[text()='Submit']"
    iframe = "//iframe[@title='Secure payment input frame']"
    verify_order = "//div[text()='Order has been placed.']"

    place_tab = "//span[text()='Places']"
    search_tb = "//input[@type='text']"
    shs_students_program = "//div[contains(text(), 'SHS - Students')]"
    shs_athletics_program = "//div[contains(text(), 'SHS - Athletics')]"
    shs_employees_vaccinated_program = "//div[contains(text(), 'SHS - Employees - Vaccinated')]"
    favourite_program = "(//div[@class='css-1dbjc4n r-1472mwg r-lrsllp'])[3]"
    un_favourite_program = "(//div[@class='css-1dbjc4n r-1472mwg r-lrsllp'])[3]"
    requirements_btn = "//div[text()= 'Requirements']"
    verify_health = "//div[@aria-label='HEALTH']"
    back_btn = "(//div[@class='css-1dbjc4n r-1awozwy r-z80fyv r-1777fci r-1kb76zh r-19wmn03'])[3]"

    record_btn = "//span[text()='Records']"
    click_dependent = "//div[@class='css-18t94o4 css-1dbjc4n r-1awozwy r-1loqt21 r-1777fci r-5scogr r-1udh08x r-bnwqim r-ipm5af']"
    first_dependent = "//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt']"
    select_dependent = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[2]"
    add_or_record_btn = "//div[text()='ADD / GET RECORD']"
    scan_document_btn = "//div[contains(text(),'Scan Document')]"
    name_tb = "(//div[@class='css-18t94o4 css-1dbjc4n r-1awozwy r-1loqt21 r-1777fci r-5scogr r-1udh08x r-bnwqim r-ipm5af'])[2]"
    first_name = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[1]"
    record_category = "(//div[@class='css-18t94o4 css-1dbjc4n r-1awozwy r-1loqt21 r-1777fci r-5scogr r-1udh08x r-bnwqim r-ipm5af'])[3]"
    record_category_health = "(//div[text()='Health'])[3]"
    record_category_id = "(//div[text()='ID'])[3]"

    record_type = "(//div[@class='css-18t94o4 css-1dbjc4n r-1awozwy r-1loqt21 r-1777fci r-5scogr r-1udh08x r-bnwqim r-ipm5af'])[4]"
    record_type_covid_pcr_test = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[1]"
    record_type_covid_vaccination = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[2]"
    record_type_covid_19_test_antigen = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[3]"
    record_type_immunization = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[4]"
    record_type_covid_19_test_antibody = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[5]"
    record_type_covid_19_rt_pcr = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[6]"

    record_type_covid_19_vaccine_shot_2 = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[7]"
    health_issuer = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[1]"
    issuer_type_cdc = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[1]"
    issuer_type_inspire_health = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[2]"
    issuer_type_inspire_health_1 = "(//div[@class='css-1dbjc4n r-14lw9ot r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt'])[1]"
    record_type_passport = "//div[text()='Passport']"
    record_type_driving_license = "//div[contains(text(), 'Driver') and contains(text(), 's License')]"
    record_type_employee_id_card = "//div[text()='Employee ID Card']"
    record_type_student_id_card = "//div[text()='Student ID Card']"
    issuer_type_passport = "//div[text()='U.S. Department of State']"
    issuer_type_texas = "(//div[contains(text(), 'Texas - Driver') and contains(text(), 's License Division')])[1]"
    issuer_type_alabama = "//div[text()='Alabama - Driver License Division']"
    issuer_type_alaska = "//div[text()='Alaska - Division of Motor Vehicles']"
    issuer_type_employee_card = "//div[text()='Dialexa Test']"
    issuer_type_student_card = "//div[text()='Dallas Independent School District']"
    issuer_tb = "(//div[@class='css-18t94o4 css-1dbjc4n r-1awozwy r-1loqt21 r-1777fci r-5scogr r-1udh08x r-bnwqim r-ipm5af'])[5]"
    click_scan = "//div[@class='css-1dbjc4n r-1kihuf0 r-14lw9ot r-1phboty r-d045u9 r-1loqt21 r-u8s1d r-1otgn73 r-1i6wzkk r-lrvibr r-1ey2ra3']"
    use_existing_btn = "//div[text()='USE EXISTING']"
    confirm_existing_document = "//div[text()='Confirm']"
    cancel_existing_document = "//div[text()='cancel']"
    save_existing_document = "//div[text()='Save']"
    cancel_doc = "(//div[contains(text(),'cancel')])[2]"
    verify_delete_record = "//div[text()='Record has been deleted.']"
    verify_record = "//div[text()='DISMISS']"

    scan = "//div[text()='scan']"
    scan_code_button = "(//div[text()='Scan Code'])[2]"
    scan_code_btn = "//div[contains(text(),'Scan Code')]"
    link_record_btn = "//div[contains(text(),'Link Record')]"
    search_records = "//div[text()='Search Records']"
    search_records_btn = "(//div[@class='css-1dbjc4n r-1awozwy r-sculcy r-z2wwpe r-156ut6 r-18u37iz r-1777fci r-5wp0in r-1yzf0co'])[2]"
    records_save_btn = "//div[text()='save']"
    records_save_bt = "(//div[@class='css-1dbjc4n r-1awozwy r-sculcy r-z2wwpe r-156ut6 r-18u37iz r-1777fci r-5wp0in r-1yzf0co'])[3]"
    health_record = "//div[@aria-label='Health']"
    select_record_button = "(//div[@class='css-1dbjc4n r-14lw9ot r-1dzdj1l r-12et9rd r-1quu1zo r-1ifxtd0 r-1h8ys4a'])[1]"
    id_record = "//div[@aria-label='ID']"
    delete_from_u_pass = "//div[text()='DELETE FROM U-PASS']"
    delete_record = "//div[text()='Delete']"

    verify_record_type_covid_pcr_test = "(//div[text()='Covid PCR Test'])[1]"
    verify_record_type_covid_vaccination = "(//div[contains(text(),'COVID-19 Vaccination')]/../../../div[2]/div[1])[1]"
    verify_record_type_covid_19_antigen = "(//div[text()='COVID-19 Antigen'])[1]"
    verify_record_type_immunization = "(//div[text()='Immunization'])[1]"
    verify_record_type_covid_19_antibody = "(//div[text()='COVID-19 Test  Antibody'])[1]"
    verify_record_type_covid_19_rt_pcr = "(//div[text()= 'COVID-19 RT-PCR'])[1]"
    verify_record_type_passport = "(//div[text()='Passport'])[1]"
    verify_record_type_texas_driver_license = "(//div[contains(text(), 'Texas - Driver') and contains(text(), 's License')])[1]"
    verify_record_type_alabama_driver_license = "(//div[text()= 'Alabama - Driver License Division'])[1]"
    verify_record_type_alaska_driver_license = "(//div[text()= 'Alaska - Division of Motor Vehicles'])[1]"
    verify_record_type_student_id_card = "(//div[text()='Dallas Independent School District'])[1]"

    forgot_password = "//a[text()='Forgot password?']"
    email_address = "//input[@name='email']"

    unique_id = "(//div[text()='YOUR UNIQUE ID'])[1]/../div[2]"
    notification_bell_icon = "(//div[@class='css-1dbjc4n r-1awozwy r-z80fyv r-1777fci r-1kb76zh r-19wmn03'])[1]"
    see_request = "(//div[text()='SEE REQUEST'])[1]"
    approve_once = "(//div[text()='Approve Once'])[1]"


class ManagerAppElements:
    continue_btn = "//div[text()='continue']"
    continue_btn_2 = "(//div[text()='continue'])[2]"
    get_started_btn = "//div[text()='get started']"

    create_new_login_btn = "//div[text()='create new login']"
    full_name = "//input[@type='text']"
    enter_email = "//input[@type='email']"
    birthdate = "//div[text()='Birthdate']//following::input[1]"
    phone_number = "(//input[@type='tel'])[1]"
    password = "(//input[@type='password'])[1]"
    confirm_password = "(//input[@type='password'])[2]"
    verify_authentication_page = "//div[text()='Two Factor']"
    go_to_upass_btn = "//div[text()='go to u-pass']"
    menu_button = "//div[text()='Programs']/../../../../div/div/div/div/div/div[1]"
    my_profile = "//div[@class='css-1dbjc4n r-1awozwy r-z2wwpe r-18u37iz r-1h0z5md r-ymttw5 r-1yzf0co']"
    verify_new_account = "//div[text()='My Account']//following::div[@class='css-901oao r-1euktgv r-1k9400p r-majxgm r-1byouvs r-1ifxtd0 r-q4m81j']"
    program_page = "//div[text()='Programs']"
    select_program_drop_down = "//div[text()='My Organizations']/../../div[2]/div/div/div/div/div/div[1]"
    select_program_shs = "//div[text()='Organizations']//following::div[@class='css-1dbjc4n r-c0fy7c r-1mq0eh r-qklmqi r-1l7z4oj r-1guathk r-1ygmrgt']"
    verify_programs = "(//div[text()='Sunset High School'])[1]"
    available_programs_active = "(//div[text()='Active'])[1]//following::div[18]"
    available_programs_inactive = "(//div[text()='Inactive'])[1]//following::div[10]"
    available_programs_draft = "(//div[text()='Draft'])[1]//following::div[3]"
    existing_account = "//div[contains(text(),'Log In to an existing account')]"
    username_tb = "//input[@id='username']"
    password_tb = "//input[@id='password']"
    sign_in_btn = "//button[contains(text(),'Continue')]"
    active_tb = "//div[text()='Programs']//following::div[21]"
    in_active_tb = "//div[text()='Programs']//following::div[28]"
    draft_tb = "//div[text()='Programs']//following::div[35]"
    select_program_shs_student = "//div[text()='SHS - Students']"
    select_program_shs_Athletics = "//div[text()='SHS - Athletics']"
    select_program_shs_Employees = "SHS - Employees - Vaccinated"
    status_active = "//div[text()='Status']/../../div/div[2]/div[2]"
    new_button = "(//div[text()='New'])[1]"
    program_name = "//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-wk8lta r-1h71sx3 r-fdjqy7 r-184en5c']"
    save_draft = "//div[text()='Save Draft']"
    verify_program_message = "//div[text()='Program has been created as a draft! Activate to publish program!']"
    verify_program = "//div[@class='css-901oao r-cqee49 r-1iy5e9m r-1x35g6 r-b88u0q r-xd6kpl r-1guathk r-q4m81j']"
    program_employees = "//div[text()='SHS - Employees - Vaccinated']"
    scan_verify = "//div[text()='Scan / Verify']"
    use_id = "//div[text()='USE ID NUMBER INSTEAD']"
    upass_id_number = "//div[text()='Enter ID Number']//following::input"
    verify_id = "//div[text()='Verify']"
    upass_verification_waiting = "//div[text()='WAITING']"
    result = "//div[text()='U-Pass Verification']/following::div[6]"
    verify_result = "//div[text()='Scan']"
    bell_icon = "//div[@class='css-1dbjc4n r-1awozwy r-z80fyv r-1777fci r-1kb76zh r-19wmn03']"
    see_request = "//div[text()='SEE REQUEST']"
    approve_once = "//div[text()='Approve Once']"
    does_not_pass = "//div[text()='Does Not Pass']"
    program_settings = "//div[text()='Program Settings']//following::div[1]"
    edit_button = "//div[text()='Edit']"
    select_status_program_setting = "(//div[text()='Program Settings'])[2]//following::div[94]"
    select_status_active = "(//div[text()='Select Status'])[4]//following::div[3]"
    select_status_inactive = "(//div[text()='Select Status'])[4]//following::div[9]"
    save_button = "//div[text()='save']"
    back_button_program_settings = "(//div[text()='Program Settings'])[2]/../../div[1]"
    back_button_directory_page_settings = "(//div[text()='Directory Page Settings'])[1]/../../div[1]"
    directory_page_settings = "//div[text()='Directory Page']//following::div[1]"
    select_status_directory = "(//div[text()='Directory Page Settings'])[2]//following::div[21]"
    select_status_unpublished = "(//div[text()='Select Status'])[4]//following::div[3]"
    select_status_published = "(//div[text()='Select Status'])[4]//following::div[9]"

    verify_program_update_message = "//div[text()='Your program has been updated!']"
    back_button_dir_page_settings = "(//div[text()='Directory Page Settings'])[2]/../../div[1]"
    program_back_button = "(//div[text()='Program Landing'])[1]/../../../../../div[2]/div[1]"
    program_name_tb = "//input[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-1mwlp6a r-crgep1 r-1mdbw0j r-779j7e r-1h71sx3 r-fdjqy7 r-184en5c']"
    description_tb = "//textarea[@class='css-11aywtz r-cqee49 r-16y2uox r-ubezar r-crgep1 r-779j7e r-1h71sx3 r-fdjqy7 r-184en5c']"
    program_shs_250 = "//div[text()='SHS-250']"
    verify_directory_page_message = "//div[text()='Changes saved successfully.']"

    swipe_program = "(//div[text()='SWIPE'])[1]"
    delete_btn = "//div[@class='css-1dbjc4n r-1loqt21 r-13awgt0 r-1777fci']/../div[1]/div/div/div"
    activate_btn = "//div[@class='css-901oao r-jwli3a r-1k9400p r-majxgm r-1byouvs r-bnwqim r-q4m81j r-73glhw' and text()='ACTIVATE']"
    deactivate_btn = "(//div[@class='css-901oao r-jwli3a r-150tq8z r-b88u0q r-1ikidpy r-1h8ys4a']/../../div[2]/div)[1]"
    delete_bt = "(//div[contains(text(), 'Delete')])[2]"

    program_card = "(//div[@class='css-1dbjc4n r-1awozwy r-14lw9ot r-z2wwpe r-1igmlmy r-1quu1zo r-13awgt0 r-18u37iz r-1777fci r-1peese0 r-1hy1u7s r-1mdbw0j'])[1]"
